use alacritty_terminal::event::VoidListener;
use alacritty_terminal::grid::Dimensions;
use alacritty_terminal::index::{Column, Line};
use alacritty_terminal::term::{Config, Term, TermDamage, TermMode};
use alacritty_terminal::vte::ansi::Processor;

#[derive(Clone, Copy)]
struct Size {
    columns: usize,
    lines: usize,
}

impl Size {
    const fn new(columns: usize, lines: usize) -> Self {
        Self { columns, lines }
    }
}

impl Dimensions for Size {
    fn total_lines(&self) -> usize {
        self.lines
    }

    fn screen_lines(&self) -> usize {
        self.lines
    }

    fn columns(&self) -> usize {
        self.columns
    }
}

fn main() {
    let mut terminal = Term::new(Config::default(), &Size::new(12, 4), VoidListener);
    let mut parser: Processor = Processor::new();

    // Exercise the normal screen and SGR before switching to the alternate screen.
    parser.advance(
        &mut terminal,
        b"primary plain \x1b[31mRED\x1b[0m\x1b[?1049h\x1b[2J\x1b[HALT \x1b[32mGREEN\x1b[0m",
    );

    // Exercise a sidecar resize while the alternate screen is active.
    terminal.resize(Size::new(16, 5));

    // Isolate damage generated by the final write so the proof shows row-level tracking.
    parser.advance(&mut terminal, b"\x1b[2;1H");
    let _ = terminal.damage();
    terminal.reset_damage();
    parser.advance(&mut terminal, b"\x1b[34mblue\x1b[0m");

    let dirty_rows = match terminal.damage() {
        TermDamage::Full => (0..terminal.screen_lines()).collect::<Vec<_>>(),
        TermDamage::Partial(lines) => lines.map(|damage| damage.line).collect(),
    };

    let columns = terminal.columns();
    let lines = terminal.screen_lines();
    let cursor = terminal.grid().cursor.point;
    let green_cell = &terminal.grid()[Line(0)][Column(4)];

    println!("engine=alacritty_terminal");
    println!("dims={columns}x{lines}");
    println!("cursor=({}, {})", cursor.column.0, cursor.line.0);
    println!(
        "alt_screen={}",
        terminal.mode().contains(TermMode::ALT_SCREEN)
    );
    println!("dirty_rows={dirty_rows:?}");
    println!("green_cell_fg={:?}", green_cell.fg);
    println!("grid:");

    for row in 0..lines {
        let text = (0..columns)
            .map(|column| terminal.grid()[Line(row as i32)][Column(column)].c)
            .collect::<String>();
        println!("{row:02} |{text}|");
    }
}
